---
app_name: lunch-api
app_namespace: lunch

# ✅ GHCR 이미지
app_image: ghcr.io/hjh6709/lunch_app_second/lunch-api:latest

app_replicas: 2
container_port: 8000

# ★ ClusterIP로 변경 (외부 노출은 Ingress Controller가 담당)
service_type: ClusterIP
service_port: 80
# node_port는 더 이상 필요 없음 (Ingress Controller가 30080 사용)
