resource "local_file" "ansible_inventory" {
  content = <<-EOT
# Ansible Inventory - Auto-generated by Terraform
# Last updated: ${timestamp()}

# ===== Host Groups =====
[master]
${aws_instance.Master_server.private_ip}

[worker]
%{for ip in aws_instance.Worker_server[*].private_ip~}
${ip}
%{endfor~}

[monitoring]
${aws_instance.monitoring_server.public_ip}

# ===== Group Hierarchy =====
[k3s_cluster:children]
master
worker

# ===== Global Variables =====
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${abspath(path.module)}/../ansible/key/Hello_kt.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# ===== Private Nodes (ProxyJump via Bastion) =====
[k3s_cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@${aws_instance.monitoring_server.public_ip} -i ${abspath(path.module)}/../ansible/key/Hello_kt.pem"'
EOT

  filename = "${path.module}/../ansible/inventory/aws.ini"

  depends_on = [
    aws_instance.Master_server,
    aws_instance.Worker_server,
    aws_instance.monitoring_server,
    local_file.ssh_key
  ]
}

# # Ansible 인벤토리 파일 자동 생성
# resource "local_file" "ansible_inventory" {
#   content = <<-EOT
# # Ansible Inventory - Auto-generated by Terraform
# # Last updated: ${timestamp()}

# # ===== Host Groups =====
# [master]
# # Master_server 리소스의 프라이빗 IP를 참조합니다.
# ${aws_instance.Master_server.private_ip} ansible_user=ubuntu ansible_ssh_private_key_file=./Hello_kt.pem

# [worker]
# # Worker_server 리소스는 count=2이므로 index [0], [1]로 가져옵니다.
# ${aws_instance.Worker_server[0].private_ip} ansible_user=ubuntu ansible_ssh_private_key_file=./Hello_kt.pem
# ${aws_instance.Worker_server[1].private_ip} ansible_user=ubuntu ansible_ssh_private_key_file=./Hello_kt.pem

# [monitoring]
# # 모니터링 서버(배스천)는 외부 접속용 public_ip를 씁니다.
# ${aws_instance.monitoring_server.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=./Hello_kt.pem

# [k3s_cluster:children]
# master
# worker

# [k3s_cluster:vars]
# ansible_user=ubuntu
# ansible_ssh_private_key_file=./Hello_kt.pem
# # ★핵심: 배스천 서버를 경유하여 프라이빗 서브넷 노드들에 접속하는 설정입니다.
# ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@${aws_instance.monitoring_server.public_ip} -i ./Hello_kt.pem"'
# EOT

#   filename = "${path.module}/ansible/inventory/aws.ini"
#   # 의존성(depends_on)도 바뀐 리소스 이름으로 수정해야 합니다.
#   depends_on = [aws_instance.Master_server, aws_instance.Worker_server, aws_instance.monitoring_server]
# }