---
- name: Install k3s server on master
  hosts: master
  become: true
  tasks:
    - name: Install common packages
      apt:
        name:
          - curl
          - ca-certificates
        state: present
        update_cache: yes

    - name: Install k3s server
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s node token
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        timeout: 120

    - name: Show master join token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: token_out

    - name: Print token (copy this if needed)
      debug:
        msg: "K3S_TOKEN={{ token_out.stdout }}"

