[master]
<MASTER_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=./Myfirstkey

[workers]
<WORKER1_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=./Myfirstkey
<WORKER2_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=./Myfirstkey

[k3s:children]
master
workers

