[master]
3.37.130.93 ansible_user=ubuntu ansible_ssh_private_key_file=./Myfirstkey

[workers]
15.164.97.224 ansible_user=ubuntu ansible_ssh_private_key_file=./Myfirstkey
43.201.68.240 ansible_user=ubuntu ansible_ssh_private_key_file=./Myfirstkey

[k3s:children]
master
workers

